/*
*Autores:
*Franklin Camacho C.I:26.796.912
*Andres Jiménez C.I: 27.212.052
*Jesús Leal C.I:26.561.030
*Elias Escalona C.I 26.568.921
*Jesús Lopez C.I 27.479.039: 
 */
package Vistas;

import java.awt.Color;

public class VAsistencia extends javax.swing.JFrame {

    public VAsistencia() {
        // Inicializa todas las variables (o mejor dicho componentes) que usa el JFrame.
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        btnBuscarMes = new javax.swing.JButton();
        jLabelCedula = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabelApellido = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtInasistencias = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtInasistenciasJus = new javax.swing.JTextField();
        txtMes = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabelFechaInicio1 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        btnBuscarCedula = new javax.swing.JButton();
        btnLimpiarMes = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabelFechaInicio2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(204, 255, 204));
        jLabel11.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel11.setText("Gestion Asistencia");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas.imagenes/00CB82.jpg"))); // NOI18N
        jLabel9.setMaximumSize(new java.awt.Dimension(252, 2));
        jLabel9.setMinimumSize(new java.awt.Dimension(252, 2));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 203, 3));

        txtAnio.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        txtAnio.setForeground(new java.awt.Color(153, 153, 153));
        txtAnio.setText("2022");
        txtAnio.setBorder(null);
        txtAnio.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnioActionPerformed(evt);
            }
        });
        jPanel1.add(txtAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 90, 20));

        btnBuscarMes.setBackground(new java.awt.Color(204, 255, 204));
        btnBuscarMes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBuscarMes.setText("Buscar");
        btnBuscarMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMesActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, -1, -1));

        jLabelCedula.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabelCedula.setText("Cedula");
        jPanel1.add(jLabelCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas.imagenes/00CB82.jpg"))); // NOI18N
        jLabel10.setMaximumSize(new java.awt.Dimension(252, 2));
        jLabel10.setMinimumSize(new java.awt.Dimension(252, 2));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 203, 3));

        txtNombre.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(153, 153, 153));
        txtNombre.setText("Nombre");
        txtNombre.setBorder(null);
        txtNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 192, 22));

        jLabelNombre.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabelNombre.setText("Nombre");
        jPanel1.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 25));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas.imagenes/00CB82.jpg"))); // NOI18N
        jLabel12.setMaximumSize(new java.awt.Dimension(252, 2));
        jLabel12.setMinimumSize(new java.awt.Dimension(252, 2));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 203, 3));

        txtApellido.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(153, 153, 153));
        txtApellido.setText("Apellido");
        txtApellido.setBorder(null);
        txtApellido.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 192, 22));

        jLabelApellido.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabelApellido.setText("Apellido");
        jPanel1.add(jLabelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, 25));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cantidad de inasistencias");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 200, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas.imagenes/00CB82.jpg"))); // NOI18N
        jLabel13.setMaximumSize(new java.awt.Dimension(252, 2));
        jLabel13.setMinimumSize(new java.awt.Dimension(252, 2));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 203, 3));

        txtInasistencias.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        txtInasistencias.setForeground(new java.awt.Color(153, 153, 153));
        txtInasistencias.setText("Ingrese las inasistencias");
        txtInasistencias.setBorder(null);
        txtInasistencias.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtInasistencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtInasistenciasMousePressed(evt);
            }
        });
        txtInasistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInasistenciasActionPerformed(evt);
            }
        });
        jPanel1.add(txtInasistencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 192, 22));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Cantidad de inasistencias justificadas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas.imagenes/00CB82.jpg"))); // NOI18N
        jLabel14.setMaximumSize(new java.awt.Dimension(252, 2));
        jLabel14.setMinimumSize(new java.awt.Dimension(252, 2));
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 203, 3));

        txtInasistenciasJus.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        txtInasistenciasJus.setForeground(new java.awt.Color(153, 153, 153));
        txtInasistenciasJus.setText("Ingrese las inasistencia justificadas");
        txtInasistenciasJus.setBorder(null);
        txtInasistenciasJus.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtInasistenciasJus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtInasistenciasJusMousePressed(evt);
            }
        });
        txtInasistenciasJus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInasistenciasJusActionPerformed(evt);
            }
        });
        jPanel1.add(txtInasistenciasJus, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 220, 22));

        txtMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el mes", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jPanel1.add(txtMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 203, -1));

        jLabel15.setMaximumSize(new java.awt.Dimension(252, 2));
        jLabel15.setMinimumSize(new java.awt.Dimension(252, 2));
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 203, 3));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Año Laboral");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas.imagenes/00CB82.jpg"))); // NOI18N
        jLabel16.setMaximumSize(new java.awt.Dimension(252, 2));
        jLabel16.setMinimumSize(new java.awt.Dimension(252, 2));
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 203, 10));

        btnAgregar.setBackground(new java.awt.Color(51, 204, 0));
        btnAgregar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 530, -1, -1));

        btnLimpiar.setBackground(new java.awt.Color(255, 102, 102));
        btnLimpiar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLimpiar.setText("Limpiar");
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 530, -1, -1));

        btnVolver.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVolver.setText("volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabelFechaInicio1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabelFechaInicio1.setText("Limpiar mes y año");
        jPanel1.add(jLabelFechaInicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, 120, 20));

        txtCedula.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        txtCedula.setForeground(new java.awt.Color(153, 153, 153));
        txtCedula.setText("Ingrese la Cedula");
        txtCedula.setBorder(null);
        txtCedula.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCedulaMousePressed(evt);
            }
        });
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        jPanel1.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 192, 22));

        btnBuscarCedula.setBackground(new java.awt.Color(153, 204, 255));
        btnBuscarCedula.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBuscarCedula.setText("Buscar");
        btnBuscarCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCedulaActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

        btnLimpiarMes.setBackground(new java.awt.Color(255, 102, 102));
        btnLimpiarMes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLimpiarMes.setText(" Limpiar");
        jPanel1.add(btnLimpiarMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas.imagenes/Login_Logo.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 80, 110));

        jLabelFechaInicio2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabelFechaInicio2.setText("Mes Laborado");
        jPanel1.add(jLabelFechaInicio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioActionPerformed

    private void btnBuscarMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarMesActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtInasistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInasistenciasActionPerformed

    }//GEN-LAST:event_txtInasistenciasActionPerformed

    private void txtInasistenciasJusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInasistenciasJusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInasistenciasJusActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed

    }//GEN-LAST:event_btnVolverActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void btnBuscarCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarCedulaActionPerformed

    private void txtCedulaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCedulaMousePressed
        if (txtCedula.getText().equals("Ingrese la Cedula")) {
            // Se le hace un set a vacío
            txtCedula.setText("");
            // Se cambia el color de la letra
            txtCedula.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtCedulaMousePressed

    private void txtInasistenciasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtInasistenciasMousePressed
        if (txtInasistencias.getText().equals("Ingrese las inasistencias")) {
            // Se le hace un set a vacío
            txtInasistencias.setText("");
            // Se cambia el color de la letra
            txtInasistencias.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtInasistenciasMousePressed

    private void txtInasistenciasJusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtInasistenciasJusMousePressed
        if (txtInasistenciasJus.getText().equals("Ingrese las inasistencia justificadas")) {
            // Se le hace un set a vacío
            txtInasistenciasJus.setText("");
            // Se cambia el color de la letra
            txtInasistenciasJus.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtInasistenciasJusMousePressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnBuscarCedula;
    public javax.swing.JButton btnBuscarMes;
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JButton btnLimpiarMes;
    public javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelCedula;
    private javax.swing.JLabel jLabelFechaInicio1;
    private javax.swing.JLabel jLabelFechaInicio2;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField txtAnio;
    public javax.swing.JTextField txtApellido;
    public javax.swing.JTextField txtCedula;
    public javax.swing.JTextField txtInasistencias;
    public javax.swing.JTextField txtInasistenciasJus;
    public javax.swing.JComboBox<String> txtMes;
    public javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
