/*
*Autores:
*Franklin Camacho C.I:26.796.912
*Andres Jiménez C.I: 27.212.052
*Jesús Leal C.I:26.561.030
*Elias Escalona C.I 26.568.921
*Jesús Lopez C.I 27.479.039: 
 */
package Vistas;

import java.awt.Color;

public class VLogin extends javax.swing.JFrame {

    // creamos variables para saber en que posición se encuenta el mouse
    int xMouse, yMouse;

    public VLogin() {
        // Inicializa todas las variables (o mejor dicho componentes) que usa el JFrame.
        initComponents();

        // Ubica el JFrame en el centro de la pantalla.
        setLocationRelativeTo(null);

        // Muestra el JFrame.
        setVisible(true);
    }

    public void addEvents(java.awt.event.ActionListener evt) {

        btnMinimizar.addActionListener(evt);
        btnMinimizar.addActionListener(evt);
        btnEntrar.addActionListener(evt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblIniciarSesion = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        lblLineaUsuario = new javax.swing.JLabel();
        lblContrasenna = new javax.swing.JLabel();
        txtContrasenna = new javax.swing.JPasswordField();
        lblLineaContrasenna = new javax.swing.JLabel();
        imgLogin = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        btnMinimizar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnEntrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setForeground(new java.awt.Color(204, 204, 204));
        Background.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Background.setMinimumSize(new java.awt.Dimension(800, 600));
        Background.setPreferredSize(new java.awt.Dimension(800, 600));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas.imagenes/Login_Logo.png"))); // NOI18N
        Background.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 520, 70, 70));

        lblIniciarSesion.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        lblIniciarSesion.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion.setText("INICIAR SESIÓN");
        Background.add(lblIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, -1));

        lblUsuario.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario.setText("USUARIO");
        Background.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));

        txtNombreUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreUsuario.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        txtNombreUsuario.setForeground(new java.awt.Color(153, 153, 153));
        txtNombreUsuario.setText("Ingrese su nombre de usuario");
        txtNombreUsuario.setBorder(null);
        txtNombreUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreUsuarioMousePressed(evt);
            }
        });
        Background.add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 370, -1));

        lblLineaUsuario.setBackground(new java.awt.Color(0, 203, 130));
        lblLineaUsuario.setForeground(new java.awt.Color(0, 203, 130));
        lblLineaUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas.imagenes/00CB82.jpg"))); // NOI18N
        Background.add(lblLineaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 380, 3));

        lblContrasenna.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        lblContrasenna.setForeground(new java.awt.Color(0, 0, 0));
        lblContrasenna.setText("CONTRASEÑA");
        Background.add(lblContrasenna, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, -1, -1));

        txtContrasenna.setBackground(new java.awt.Color(255, 255, 255));
        txtContrasenna.setForeground(new java.awt.Color(153, 153, 153));
        txtContrasenna.setText("********");
        txtContrasenna.setBorder(null);
        txtContrasenna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtContrasennaMousePressed(evt);
            }
        });
        Background.add(txtContrasenna, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 380, -1));

        lblLineaContrasenna.setBackground(new java.awt.Color(0, 203, 130));
        lblLineaContrasenna.setForeground(new java.awt.Color(0, 203, 130));
        lblLineaContrasenna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas.imagenes/5FFFD9.jpg"))); // NOI18N
        Background.add(lblLineaContrasenna, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 380, 3));

        imgLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas.imagenes/Login_BG.png"))); // NOI18N
        Background.add(imgLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 600));

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMinimizar.setBackground(new java.awt.Color(255, 255, 255));
        btnMinimizar.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        btnMinimizar.setText("_");
        btnMinimizar.setBorder(null);
        btnMinimizar.setBorderPainted(false);
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.setPreferredSize(new java.awt.Dimension(40, 40));
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseExited(evt);
            }
        });
        Header.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, -1, -1));

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        btnSalir.setText("X");
        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setPreferredSize(new java.awt.Dimension(40, 40));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        Header.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, -1, -1));

        Background.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        btnEntrar.setBackground(new java.awt.Color(38, 172, 239));
        btnEntrar.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setText("ENTRAR");
        btnEntrar.setBorder(null);
        btnEntrar.setBorderPainted(false);
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntrar.setPreferredSize(new java.awt.Dimension(170, 50));
        btnEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEntrarMouseExited(evt);
            }
        });
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        Background.add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, 380, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        // Obtenemos la posición del Mouse en la pantalla en el eje X
        int x = evt.getXOnScreen();

        // Obtenemos la posición del Mouse en la pantalla en el eje Y
        int y = evt.getYOnScreen();

        // Movemos la pantalla a la posición especificada
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_HeaderMouseDragged

    // Cuando el mouse entra dentro del Boton
    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        // Se cambia el color a Rojo
        btnSalir.setBackground(Color.red);
        btnSalir.setForeground(Color.white);
    }//GEN-LAST:event_btnSalirMouseEntered

    // Cuando el boton de salir sea clickeado
    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // Se cierra el sistema
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    // Cuando el mouse salga del Boton Salir
    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        btnSalir.setBackground(Color.white);
        btnSalir.setForeground(Color.black);
    }//GEN-LAST:event_btnSalirMouseExited

    // Cuando el boton de minimizar es pulsado
    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        //this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizarMouseClicked
    // Cuando el mouse sale del boton minimizar
    private void btnMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseExited
        btnMinimizar.setBackground(Color.white);
        btnMinimizar.setForeground(Color.black);
    }//GEN-LAST:event_btnMinimizarMouseExited

    // Cuando el mouse ingrese al boton de Minimizar
    private void btnMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseEntered
        btnMinimizar.setBackground(Color.GRAY);
        btnMinimizar.setForeground(Color.white);
    }//GEN-LAST:event_btnMinimizarMouseEntered
    // Cuando el mouse ingrese al boton "entrar"
    private void btnEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseEntered
        btnEntrar.setBackground(new java.awt.Color(15, 38, 109));
    }//GEN-LAST:event_btnEntrarMouseEntered

    // Cuando el mouse salga del boton "entrar"
    private void btnEntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseExited
        btnEntrar.setBackground(new java.awt.Color(38, 172, 239));
    }//GEN-LAST:event_btnEntrarMouseExited

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntrarActionPerformed

    // Cuando el mouse de click en el campo de usuario
    private void txtNombreUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreUsuarioMousePressed
        if (txtNombreUsuario.getText().equals("Ingrese su nombre de usuario")) {
            txtNombreUsuario.setText("");
            txtNombreUsuario.setForeground(Color.black);
        }
        if (String.valueOf(txtContrasenna.getPassword()).isEmpty()) {
            txtContrasenna.setText("********");
            txtContrasenna.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtNombreUsuarioMousePressed

    // Cuando el mouse de click en el campo de contraseña
    private void txtContrasennaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContrasennaMousePressed
        if (String.valueOf(txtContrasenna.getPassword()).equals("********")) {
            txtContrasenna.setText("");
            txtContrasenna.setForeground(Color.black);
        }
        if (txtNombreUsuario.getText().isEmpty()) {
            txtNombreUsuario.setForeground(Color.gray);
            txtNombreUsuario.setText("Ingrese su nombre de usuario");
        }
    }//GEN-LAST:event_txtContrasennaMousePressed

    // Si se da click a boton "entrar"
    private void btnEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseClicked
        // Se obtiene la contraseña ingresada.
        char[] password = txtContrasenna.getPassword();
        // Se transforma la contraseña a String
        String pass = new String(password);
        if ("admin".equals(txtNombreUsuario.getText()) && "admin".equals(pass)) {

        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Credenciales incorrectas, intente de nuevo",
                    "Error en Inicio de Sesión",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEntrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new RunnableImpl());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    public javax.swing.JPanel Header;
    public javax.swing.JButton btnEntrar;
    public javax.swing.JButton btnMinimizar;
    public javax.swing.JButton btnSalir;
    private javax.swing.JLabel imgLogin;
    private javax.swing.JLabel lblContrasenna;
    private javax.swing.JLabel lblIniciarSesion;
    private javax.swing.JLabel lblLineaContrasenna;
    private javax.swing.JLabel lblLineaUsuario;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblUsuario;
    public javax.swing.JPasswordField txtContrasenna;
    public javax.swing.JTextField txtNombreUsuario;
    // End of variables declaration//GEN-END:variables

    private static class RunnableImpl implements Runnable {

        public RunnableImpl() {
        }

        @Override
        public void run() {
            new VLogin().setVisible(true);
        }
    }
}
