/*
*Autores:
*Franklin Camacho C.I:26.796.912
*Andres Jiménez C.I: 27.212.052
*Jesús Leal C.I:26.561.030
*Elias Escalona C.I 26.568.921
*Jesús Lopez C.I 27.479.039: 
 */
package Vistas;

import java.awt.Color;

public class VVigilanteConsulta extends javax.swing.JFrame {

    public VVigilanteConsulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        btnMinimizar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        lblCedula = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        lblGestionVigilante = new javax.swing.JLabel();
        lblCedula1 = new javax.swing.JLabel();
        txtCedula1 = new javax.swing.JTextField();
        lblCedula2 = new javax.swing.JLabel();
        txtCedula2 = new javax.swing.JTextField();
        lblCedula3 = new javax.swing.JLabel();
        txtCedula3 = new javax.swing.JTextField();
        lblCedula4 = new javax.swing.JLabel();
        txtCedula4 = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        txtMes = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabelFechaInicio2 = new javax.swing.JLabel();
        btnBuscarMes = new javax.swing.JButton();
        lblCedula5 = new javax.swing.JLabel();
        txtCedula5 = new javax.swing.JTextField();
        lblCedula6 = new javax.swing.JLabel();
        txtCedula6 = new javax.swing.JTextField();
        txtCedula7 = new javax.swing.JTextField();
        lblCedula7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolver.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas.imagenes/Iconos/IconVolver.png"))); // NOI18N
        btnVolver.setBorder(null);
        btnVolver.setBorderPainted(false);
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.setHideActionText(true);
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverMouseExited(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnMinimizar.setBackground(new java.awt.Color(255, 255, 255));
        btnMinimizar.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        btnMinimizar.setText("_");
        btnMinimizar.setBorder(null);
        btnMinimizar.setBorderPainted(false);
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.setPreferredSize(new java.awt.Dimension(40, 40));
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseExited(evt);
            }
        });
        jPanel1.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, -1, -1));

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        btnSalir.setText("X");
        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setPreferredSize(new java.awt.Dimension(40, 40));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, -1, -1));

        btnBuscar.setBackground(new java.awt.Color(38, 172, 239));
        btnBuscar.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas.imagenes/Iconos/IconBuscar.png"))); // NOI18N
        btnBuscar.setBorder(null);
        btnBuscar.setBorderPainted(false);
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMouseExited(evt);
            }
        });
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        lblCedula.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        lblCedula.setText("Cedula");
        jPanel1.add(lblCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        txtCedula.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        txtCedula.setForeground(new java.awt.Color(153, 153, 153));
        txtCedula.setText("Ingrese la Cedula");
        txtCedula.setBorder(null);
        txtCedula.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCedulaMousePressed(evt);
            }
        });
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        jPanel1.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 165, 20));

        lblGestionVigilante.setBackground(new java.awt.Color(255, 255, 255));
        lblGestionVigilante.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        lblGestionVigilante.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGestionVigilante.setText("Consulta vigilante");
        jPanel1.add(lblGestionVigilante, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 300, -1));

        lblCedula1.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        lblCedula1.setText("Dias trabajados");
        jPanel1.add(lblCedula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, -1));

        txtCedula1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        txtCedula1.setForeground(new java.awt.Color(153, 153, 153));
        txtCedula1.setText("Dias trabajados");
        txtCedula1.setBorder(null);
        txtCedula1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCedula1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCedula1MousePressed(evt);
            }
        });
        txtCedula1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedula1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtCedula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 165, 20));

        lblCedula2.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        lblCedula2.setText("Horas extras trabajadas");
        jPanel1.add(lblCedula2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, -1, -1));

        txtCedula2.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        txtCedula2.setForeground(new java.awt.Color(153, 153, 153));
        txtCedula2.setText("Horas extras trabajadas");
        txtCedula2.setBorder(null);
        txtCedula2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCedula2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCedula2MousePressed(evt);
            }
        });
        txtCedula2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedula2ActionPerformed(evt);
            }
        });
        jPanel1.add(txtCedula2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 165, 20));

        lblCedula3.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        lblCedula3.setText("Ausencia semana 1");
        jPanel1.add(lblCedula3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, -1, -1));

        txtCedula3.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        txtCedula3.setForeground(new java.awt.Color(153, 153, 153));
        txtCedula3.setText("Ausencia semanal");
        txtCedula3.setBorder(null);
        txtCedula3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCedula3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCedula3MousePressed(evt);
            }
        });
        txtCedula3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedula3ActionPerformed(evt);
            }
        });
        jPanel1.add(txtCedula3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 165, 20));

        lblCedula4.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        lblCedula4.setText("Ausencia mensual");
        jPanel1.add(lblCedula4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, -1, -1));

        txtCedula4.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        txtCedula4.setForeground(new java.awt.Color(153, 153, 153));
        txtCedula4.setText("Ausencia mensual");
        txtCedula4.setBorder(null);
        txtCedula4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCedula4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCedula4MousePressed(evt);
            }
        });
        txtCedula4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedula4ActionPerformed(evt);
            }
        });
        jPanel1.add(txtCedula4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, 165, 20));

        txtAnio.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        txtAnio.setForeground(new java.awt.Color(153, 153, 153));
        txtAnio.setText("2022");
        txtAnio.setBorder(null);
        txtAnio.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnioActionPerformed(evt);
            }
        });
        jPanel1.add(txtAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 90, 20));

        txtMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el mes", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jPanel1.add(txtMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 203, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Año Laboral");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas.imagenes/00CB82.jpg"))); // NOI18N
        jLabel16.setMaximumSize(new java.awt.Dimension(252, 2));
        jLabel16.setMinimumSize(new java.awt.Dimension(252, 2));
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 203, 10));

        jLabelFechaInicio2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabelFechaInicio2.setText("Mes Laborado");
        jPanel1.add(jLabelFechaInicio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        btnBuscarMes.setBackground(new java.awt.Color(204, 255, 204));
        btnBuscarMes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBuscarMes.setText("Buscar");
        btnBuscarMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMesActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 120, 40));

        lblCedula5.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        lblCedula5.setText("Ausencia semana 2");
        jPanel1.add(lblCedula5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, -1, -1));

        txtCedula5.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        txtCedula5.setForeground(new java.awt.Color(153, 153, 153));
        txtCedula5.setText("Ausencia semanal");
        txtCedula5.setBorder(null);
        txtCedula5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCedula5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCedula5MousePressed(evt);
            }
        });
        txtCedula5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedula5ActionPerformed(evt);
            }
        });
        jPanel1.add(txtCedula5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 165, 20));

        lblCedula6.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        lblCedula6.setText("Ausencia semana 3");
        jPanel1.add(lblCedula6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, -1, -1));

        txtCedula6.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        txtCedula6.setForeground(new java.awt.Color(153, 153, 153));
        txtCedula6.setText("Ausencia semanal");
        txtCedula6.setBorder(null);
        txtCedula6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCedula6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCedula6MousePressed(evt);
            }
        });
        txtCedula6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedula6ActionPerformed(evt);
            }
        });
        jPanel1.add(txtCedula6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 165, 20));

        txtCedula7.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        txtCedula7.setForeground(new java.awt.Color(153, 153, 153));
        txtCedula7.setText("Ausencia semanal");
        txtCedula7.setBorder(null);
        txtCedula7.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCedula7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCedula7MousePressed(evt);
            }
        });
        txtCedula7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedula7ActionPerformed(evt);
            }
        });
        jPanel1.add(txtCedula7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 165, 20));

        lblCedula7.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        lblCedula7.setText("Ausencia semana 4");
        jPanel1.add(lblCedula7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseEntered
        // Se cambia el color de fondo del boton a cyan
        btnVolver.setBackground(Color.cyan);

        // Se cambio el color de la letra a blanco del boton
        btnVolver.setForeground(Color.white);
    }//GEN-LAST:event_btnVolverMouseEntered

    private void btnVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseExited
        // Se cambia el color de fondo del boton al original
        btnVolver.setBackground(Color.white);

        // Se cambia el color de la letra del boton a negro
        btnVolver.setForeground(Color.black);
    }//GEN-LAST:event_btnVolverMouseExited

    private void btnMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseEntered
        btnMinimizar.setBackground(Color.GRAY);
        btnMinimizar.setForeground(Color.white);
    }//GEN-LAST:event_btnMinimizarMouseEntered

    private void btnMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseExited
        btnMinimizar.setBackground(Color.white);
        btnMinimizar.setForeground(Color.black);
    }//GEN-LAST:event_btnMinimizarMouseExited

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        // Se cambia el color a Rojo
        btnSalir.setBackground(Color.red);
        btnSalir.setForeground(Color.white);
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        btnSalir.setBackground(Color.white);
        btnSalir.setForeground(Color.black);
    }//GEN-LAST:event_btnSalirMouseExited

    private void btnBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseEntered
        btnBuscar.setBackground(new java.awt.Color(0, 203, 130));
    }//GEN-LAST:event_btnBuscarMouseEntered

    private void btnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseExited
        btnBuscar.setBackground(new java.awt.Color(38, 172, 239));
    }//GEN-LAST:event_btnBuscarMouseExited

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtCedulaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCedulaMousePressed
        // Si el campo tiene el valor por defecto
        if (txtCedula.getText().equals("Ingrese la Cedula")) {
            // Se le hace un set a vacío
            txtCedula.setText("");
            // Se cambia el color de la letra
            txtCedula.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtCedulaMousePressed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtCedula1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCedula1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedula1MousePressed

    private void txtCedula1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedula1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedula1ActionPerformed

    private void txtCedula2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCedula2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedula2MousePressed

    private void txtCedula2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedula2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedula2ActionPerformed

    private void txtCedula3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCedula3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedula3MousePressed

    private void txtCedula3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedula3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedula3ActionPerformed

    private void txtCedula4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCedula4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedula4MousePressed

    private void txtCedula4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedula4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedula4ActionPerformed

    private void txtAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioActionPerformed

    private void btnBuscarMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarMesActionPerformed

    private void txtCedula5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCedula5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedula5MousePressed

    private void txtCedula5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedula5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedula5ActionPerformed

    private void txtCedula6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCedula6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedula6MousePressed

    private void txtCedula6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedula6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedula6ActionPerformed

    private void txtCedula7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCedula7MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedula7MousePressed

    private void txtCedula7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedula7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedula7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VVigilanteConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VVigilanteConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VVigilanteConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VVigilanteConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VVigilanteConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnBuscarMes;
    public javax.swing.JButton btnMinimizar;
    public javax.swing.JButton btnSalir;
    public javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelFechaInicio2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCedula1;
    private javax.swing.JLabel lblCedula2;
    private javax.swing.JLabel lblCedula3;
    private javax.swing.JLabel lblCedula4;
    private javax.swing.JLabel lblCedula5;
    private javax.swing.JLabel lblCedula6;
    private javax.swing.JLabel lblCedula7;
    private javax.swing.JLabel lblGestionVigilante;
    public javax.swing.JTextField txtAnio;
    public javax.swing.JTextField txtCedula;
    public javax.swing.JTextField txtCedula1;
    public javax.swing.JTextField txtCedula2;
    public javax.swing.JTextField txtCedula3;
    public javax.swing.JTextField txtCedula4;
    public javax.swing.JTextField txtCedula5;
    public javax.swing.JTextField txtCedula6;
    public javax.swing.JTextField txtCedula7;
    public javax.swing.JComboBox<String> txtMes;
    // End of variables declaration//GEN-END:variables
}
